version: 2.1
jobs:
  build:
    working_directory: ~/flexitem
    docker:
      - image: circleci/node:14.15.4
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "package.json" }}
      - run:
          name: Install
          command: npm install
      - save_cache:
          key: dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: EsLint
          command: npm run lint
      - run: 
          name: StyleLint
          command: npm run lint:css
